# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/OR_GATE.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/HA.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/FA_comb.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/three_way_or.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/RCA.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/FA_seq_beh.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/FA_seq.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/FA_COMB_behav.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/AND_GATE.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/BCD_ADDER.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/BCD_PA.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/RCA_pipe.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/mul_pipe.vhd
  C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.srcs/sources_1/new/full_adder_star.vhd
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Superminiala/Documents/VLSI/Lab_2/Lab_2.cache/wt [current_project]
set_property parent.project_dir C:/Users/Superminiala/Documents/VLSI/Lab_2 [current_project]
catch { write_hwdef -file mul_pipe.hwdef }
synth_design -top mul_pipe -part xc7z010clg400-1
write_checkpoint mul_pipe.dcp
report_utilization -file mul_pipe_utilization_synth.rpt -pb mul_pipe_utilization_synth.pb
