# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib C:/Users/Superminiala/Downloads/B_3/B_3.srcs/sources_1/new/up_counter_with_upper_limit.vhd
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Superminiala/Downloads/B_3/B_3.cache/wt [current_project]
set_property parent.project_dir C:/Users/Superminiala/Downloads/B_3 [current_project]
catch { write_hwdef -file Up_Counter_With_Upper_Limit.hwdef }
synth_design -top Up_Counter_With_Upper_Limit -part xc7z010clg400-1
write_checkpoint Up_Counter_With_Upper_Limit.dcp
report_utilization -file Up_Counter_With_Upper_Limit_utilization_synth.rpt -pb Up_Counter_With_Upper_Limit_utilization_synth.pb
